name: lint_code_shell
on:
  push:
    branches:
      - 'task2'
  pull_request:
    branches:
      - 'task2'
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v4
